from __future__ import annotations

import base64
import json

from app.domain.project import ProjectSpec
from app.domain.workflow import ExportFormat, ExportResult
from app.services.litematica import write_litematic
from app.services.merger import MergeResult


class Exporter:
    def export(
        self,
        project_id: str,
        format_name: ExportFormat,
        merge_result: MergeResult,
        spec: ProjectSpec,
    ) -> ExportResult:
        if format_name == "litematica":
            return self._export_litematica(project_id, merge_result, spec)
        if format_name == "json":
            return self._export_json(project_id, merge_result)
        return self._export_mcfunction(project_id, merge_result)

    def _export_litematica(
        self,
        project_id: str,
        merge_result: MergeResult,
        spec: ProjectSpec,
    ) -> ExportResult:
        size = spec.project.size
        origin = spec.project.origin
        name = spec.project.name
        data = write_litematic(name, merge_result, size, origin)
        return ExportResult(
            project_id=project_id,
            format="litematica",
            file_name=f"{project_id}.litematic",
            content=base64.b64encode(data).decode("ascii"),
        )

    def _export_json(self, project_id: str, merge_result: MergeResult) -> ExportResult:
        payload = {
            "project_id": project_id,
            "block_count": len(merge_result.global_blocks),
            "blocks": [
                {"x": x, "y": y, "z": z, "block": block_id, "region": merge_result.block_region_map[(x, y, z)]}
                for (x, y, z), block_id in sorted(merge_result.global_blocks.items())
            ],
        }
        return ExportResult(
            project_id=project_id,
            format="json",
            file_name=f"{project_id}.json",
            content=json.dumps(payload, indent=2),
        )

    def _export_mcfunction(self, project_id: str, merge_result: MergeResult) -> ExportResult:
        lines = [
            "# Auto-generated by mcAgentBuilder",
            f"# project: {project_id}",
            f"# blocks: {len(merge_result.global_blocks)}",
            "",
        ]
        for (x, y, z), block_id in sorted(merge_result.global_blocks.items()):
            if block_id == "minecraft:air":
                continue
            lines.append(f"setblock {x} {y} {z} {block_id}")
        return ExportResult(
            project_id=project_id,
            format="mcfunction",
            file_name=f"{project_id}.mcfunction",
            content="\n".join(lines) + "\n",
        )
